<?php
$router->get('/cronForNextCourseAssignment','CourseController@cronForNextCourseAssignment');
$router->get('/cronToSetExpireCourses','CourseController@cronToSetExpireCourses'); 
$router->get('/autoReminderCron','CourseController@autoReminderCron');
$router->get('/resourceMigration','CourseController@resourceMigration');    
$router->get('/weeklyProgressreport','CourseController@weeklyProgressreport');
$router->get('/dailyReport', 'CourseController@dailyReport');

$router->get('/testCron','CourseController@testCron'); 
$router->group(['middleware' => 'auth'],function () use ($router) {
    $router->post('/', 'CourseController@create');
    $router->get('/all', 'CourseController@allCourses');
    $router->post('/unassignedCourses', 'CourseController@unassignedCoursess');
    $router->post('/all_courses', 'CourseController@readAll');
    $router->post('/allcourse_folders','CourseController@allCourseFolders');
    $router->get('/all_course', 'CourseController@allCourse');
    $router->get('/all_activecourses','CourseController@getAllCourses');
    $router->get('/duplicate/{id}','CourseController@duplicate');
    $router->get('/edit/{id}','CourseController@edit');
    $router->put('/update/{id}','CourseController@update');
    $router->delete('/delete/{id}','CourseController@destroy');
    $router->get('/passed_msg','CourseController@coursePassedMsg');
    $router->get('/unassignedCertificates','CourseController@unassignedCertificates');
    $router->get('/surveytests','CourseController@surveytests');
    $router->post('/certificate','CourseController@addCertificate');
    $router->get('/certificate','CourseController@readAllCertificates');
    $router->get('/certificate/{id}','CourseController@editCertificate');
    $router->put('/certificate/{id}','CourseController@updateCertificate');
    $router->delete('/certificate/{id}/{isCertificate}','CourseController@destoryCertificate');
    $router->delete('/unassigncertificate/{id}/{course_id}','CourseController@unassignCertificate');
    $router->post('/coursefolder','CourseController@addCourseFolder');
    $router->put('/coursefolder/{id}','CourseController@updateCourseFolder');
    $router->get('/coursefolder/{id}','CourseController@editCourseFolder');
    $router->delete('/coursefolder/{id}','CourseController@destoryCourseFolder');
    $router->delete('/removecoursefolder/{id}','CourseController@removeCourseFolder');
    $router->post('/assignCourseFolder','CourseController@assignCourseFolder');
    $router->post('/foldercourses','CourseController@folderCourses');
    $router->post('/test','CourseController@addTest');
    $router->post('/lesson','CourseController@addLesson');
    $router->post('/read_file','CourseController@readFile');
    $router->put('/lesson/{id}','CourseController@updateLesson');
    $router->post('/updatelesson','CourseController@updateLesson');
    $router->delete('/lesson/{id}','CourseController@deleteLesson');
    $router->put('/test/{id}','CourseController@updateTest');
    $router->delete('/test/{id}','CourseController@deleteTest');
    $router->delete('/question/{id}','CourseController@deleteQuestion');
    $router->post('/resources','CourseController@resources');
    $router->delete('/resources/{id}','CourseController@deleteresources');
    $router->delete('/question_answer/{id}','CourseController@deleteQuestionOption');
    $router->get('/certificatesList','CourseController@certificatesList');
    $router->post('/certificatesList','CourseController@certificatesFilterList');
    $router->get('/certificates','CourseController@allCertificates');
    $router->post('/update_resource','CourseController@updateResource');
    $router->post('/assign','CourseController@courseAssignment');
    $router->post('/assign_email','CourseController@assignEmail');
    $router->post('/unassign','CourseController@courseUnassignment');
    $router->put('/update_status/{id}','CourseController@updateStatus');
    $router->put('/update_folder_status/{id}','CourseController@updateFolderStatus');
    $router->post('/employees','CourseController@courseEmployees');
    $router->post('/delete_location','CourseController@deleteLocation');
    $router->post('/full_data','CourseController@courseData');
    $router->post('/gamification_data','CourseController@gamificationData');
    $router->post('/submit','CourseController@courseSubmit');
    $router->post('/generate_certificate','CourseController@generateCertificate');
    $router->post('/download_certificates','CourseController@downloadCerts');
    $router->get('/certificate','CourseController@certificate');
    $router->post('/un_assign','CourseController@unassignCourse');
    $router->post('/companies','CourseController@companies');
    $router->post('/pass_employee','CourseController@passEmployees');
    $router->post('/pass_employee_excel','CourseController@passEmployeesExcel');
    $router->get('/download_certificate/{id}','CourseController@downloadCertificates');
    $router->post('/print_certificates','CourseController@PrintCertificates');
    $router->post('/courses_excel','CourseController@coursesExcel');
    $router->post('/totalpassedtest','CourseController@totalPassedCourse');
    $router->post('/certificates/report','CourseController@certificateReport');
    $router->post('/preTest','CourseController@preTest'); 
    $router->put('/preTestUpdate/{id}','CourseController@preTestUpdate');
    $router->delete('/pretest/{id}','CourseController@preTestDelete');
    $router->post('/readQuestionAnswer','CourseController@readQuestionAnswer'); 
    $router->get('/templates', 'CourseController@templates');    
    $router->post('/createSurvey','SurveyController@createSurvey'); 
    $router->put('/editSurvey/{id}','SurveyController@editSurvey');
    $router->get('/getSurvey','SurveyController@getSurvey'); 
    $router->post('/employeeAnswer','CourseController@employeeAnswer'); 
    $router->post('/assignnextcourse','CourseController@assignnextcourse'); 
    $router->delete('/surveytest/{id}/{course_id}','SurveyController@deleteSurvey'); 
    $router->post('/practiceTestAnswers','CourseController@practiceTestAnswers');
    $router->post('/test_question_report','CourseController@TestQuestionReport');
    $router->post('/survey_report','CourseController@surveyReport');
    $router->post('/survey_submission_report','CourseController@surveySubmissionReport');
    $router->post('/survey_submission_report_details','CourseController@surveySubmissionReportDetails');
    $router->post('/proctored-exam', 'CourseController@proctoredExam');
    $router->post('/proctored-exam-certificate', 'CourseController@proctoredExamCertificate');
    $router->post('/pay_by_employee_submission','CourseController@payByEmployeeSubmission');
    $router->post('/fail_pass_report','CourseController@failPassReport');
    $router->get('/category', 'CourseController@courseCategories'); 
    
});
$router->post('/proctored-exam-callback', 'CourseController@proctoredExamCallback');
$router->post('/updateTimerValue','CourseController@updateTimerValue');
$router->get('/update-old-course-history-record','CourseController@updateOldCourseHistoryRecord');